theme: jekyll-theme-slate
title: Ethan Payne
subtitle: Honours Student at Monash University
description: Welcome to my website! Here I present some of the interesting research I have been undertaking in the field of gravitational-wave astrophysics!
